# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 039eeb22db7ca3efa5beec395b92bd9dd22858952bae4d27f2220ffc2fe47c56053c4710cbfa3d0ed418476a9cd78111cbbee62e35fa4e23695b33dc4ac1c361

test:
  secret_key_base: c5f8538b1d267f3ff41a79fd23155c41539e7109d68de2812907766a68dab81953dc948261f0bf6193affb780dd604ce484170b476f2e5ac6e4c6961740278ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
